### PR TITLE
Luisfer

### PR DESCRIPTION
**Pull request by LuisferGuevara**
I´ve just styled the Login Section, like it?

### CODE REVIEW

**Review by Karuh13 — CHANGES_REQUESTED** [review]
Put the Register back, you punk!

**Comment by JaimeSdD** [comment]
Cammon guys, the register was a good guy

**Comment by LuisferGuevara** [comment]
Here's your beloved Register bro!

**Review by Karuh13 — APPROVED** [review]
I'm sorry bro, I got all heated up

**Pull request merged**
